// Menu content transcribed from the printed menu images (single source of truth
// for the on-page text menu and the schema.org hasMenu structured data).
// Prices are strings to support "lunch / dinner" style dual pricing.

export interface MenuItem {
  name: string;
  price: string;
  description?: string;
  spicy?: boolean;
}

export interface MenuSection {
  title: string;
  note?: string;
  items: MenuItem[];
}

const fernieMenu: MenuSection[] = [
  {
    title: "Appetizers",
    items: [
      { name: "House Made Kimchi", price: "7" },
      { name: "Edamame", price: "6" },
      { name: "Gomae Salad", price: "7.5", description: "Spinach" },
      { name: "Seaweed Salad", price: "8" },
      { name: "House Salad", price: "10" },
      { name: "Spicy Sashimi Salad", price: "19", description: "Assorted sashimi with mixed greens and a spicy sauce", spicy: true },
      { name: "Agedashi Tofu", price: "8.5", description: "(6pc) Crispy fried tofu with teriyaki sauce" },
      { name: "Spicy Agedashi Tofu", price: "9.5", description: "(6pc) Crispy fried tofu with a spicy sauce", spicy: true },
      { name: "Takoyaki", price: "10.5", description: "(6pc) Octopus" },
      { name: "Pork/Veggie Gyoza", price: "10.5", description: "(6pc) Deep fried" },
      { name: "Spicy Pork Gyoza", price: "11.5", description: "(6pc)", spicy: true },
      { name: "Chicken Karaage", price: "13.5" },
      { name: "Soft Shell Crab", price: "17", description: "Deep fried soft shell crab" },
      { name: "Calamari", price: "13", description: "Deep fried squid" },
      { name: "Vegetable Spring Roll", price: "12", description: "(6pc)" },
      { name: "Ebi Sunomono", price: "9.25" },
      { name: "Vegetable Sunomono", price: "8.25" },
      { name: "Crunchy Jalapeno", price: "12.5", description: "Crispy fried jalapeno with tuna", spicy: true },
      { name: "Spicy Chicken", price: "18.5", description: "Deep fried chicken with homemade sauce", spicy: true },
      { name: "Monkey Brain", price: "17", description: "Whole avocado deep fried & filled with spicy tuna & crab meat", spicy: true },
      { name: "Prawn Tempura", price: "12.5", description: "(4pc)" },
      { name: "Veggie Tempura", price: "12", description: "(5pc)" },
      { name: "Mixed Tempura", price: "12", description: "(5pc)" },
      { name: "Yam Tempura", price: "10", description: "(4pc)" },
      { name: "Rice", price: "4" },
      { name: "Miso", price: "3.5" },
    ],
  },
  {
    title: "Nigiri",
    note: "2 pcs — Aburi nigiri (1pc) +.50",
    items: [
      { name: "Tamago (Egg)", price: "6" },
      { name: "Ebi (Cooked Prawn)", price: "7" },
      { name: "Tako (Octopus)", price: "8" },
      { name: "Kani (Real Crab)", price: "6" },
      { name: "Chopped Scallop", price: "8" },
      { name: "Avocado", price: "5.5" },
      { name: "Ikura (Salmon Roe)", price: "13" },
      { name: "Tobiko (Flying Fish Roe)", price: "8" },
      { name: "Salmon Atlantic", price: "7" },
      { name: "Tuna Albacore", price: "7" },
      { name: "Sockeye Salmon", price: "8" },
      { name: "Ahi Tuna", price: "10" },
      { name: "Ika (Squid)", price: "7" },
      { name: "Tai", price: "7" },
      { name: "Toro (Tuna Belly)", price: "9" },
      { name: "Unagi (Eel)", price: "8" },
      { name: "Inari", price: "7" },
      { name: "Inari with Salmon", price: "8.5" },
      { name: "Inari with Avocado & Salmon", price: "9" },
    ],
  },
  {
    title: "Sashimi",
    note: "4 pcs / 8 pcs",
    items: [
      { name: "Salmon Atlantic", price: "12 / 23" },
      { name: "Tuna Albacore", price: "13 / 25" },
      { name: "Toro (Tuna Belly)", price: "12.5 / 24" },
      { name: "Unagi (Eel)", price: "12 / 23" },
      { name: "Spicy Tuna", price: "14 / 27", spicy: true },
      { name: "Tako (Octopus)", price: "12.5 / 24" },
      { name: "Sockeye Salmon", price: "16 / 30" },
      { name: "Ahi Tuna", price: "22 / 40" },
      { name: "Spicy Salmon", price: "13 / 24", spicy: true },
      { name: "Tuna Tataki", price: "13 / 25" },
      { name: "Appetizer (7 pcs)", price: "19.95" },
      { name: "Assorted (9 pcs)", price: "29" },
      { name: "Chef (20 pcs)", price: "59" },
    ],
  },
  {
    title: "Rolls",
    items: [
      { name: "Cucumber Maki", price: "6" },
      { name: "Avocado Maki", price: "6.5" },
      { name: "Salmon Maki", price: "7" },
      { name: "Tuna Maki", price: "7" },
      { name: "Vegetable", price: "8", description: "Cucumber, avocado, asparagus & yam" },
      { name: "BC", price: "9.5", description: "Salmon skin, cucumber & crabmeat with unagi sauce" },
      { name: "California", price: "8.5", description: "Cucumber, avocado & crabmeat" },
      { name: "Real Crab California", price: "11.95", description: "Real crab, avocado & cucumber with mayo" },
      { name: "Fresh Vegetable", price: "7.5", description: "Cucumber, avocado, carrot, beet, salad & radish" },
      { name: "Yam Tempura Roll", price: "8.5", description: "Yam roll with sweet mayo" },
      { name: "Tempura", price: "9", description: "(2pc) Prawn tempura & avocado with unagi sauce" },
      { name: "Asparagus", price: "9", description: "(3pc) Deep fried asparagus & avocado" },
      { name: "Tofu", price: "7.5", description: "Deep fried tofu with sweet mayo & unagi sauce" },
      { name: "Avocado & Cucumber", price: "9" },
      { name: "Avocado & Tuna", price: "10" },
      { name: "Avocado & Salmon", price: "10.5" },
      { name: "Avocado & Mango", price: "9" },
      { name: "Negitoro", price: "10.5", description: "Toro & green onion" },
      { name: "Unagi", price: "10", description: "Eel, cucumber, avocado & crabmeat with unagi sauce" },
      { name: "Crazy Veggie", price: "10.5", description: "Assorted veggie tempura with unagi sauce" },
      { name: "Spicy Salmon Tempura", price: "10.5", description: "Salmon tempura roll with unagi & spicy mayo sauce", spicy: true },
      { name: "Spicy Tuna Tempura", price: "10.5", description: "Tuna tempura, cucumber & crabmeat with spicy & unagi sauce", spicy: true },
      { name: "Chopped Scallop", price: "9.5", description: "Scallop, cucumber & sweet mayo sauce" },
      { name: "Spicy Salmon", price: "9.5", description: "Raw salmon & cucumber with spicy mayo sauce", spicy: true },
      { name: "Spicy Tuna", price: "9.5", description: "Raw tuna & cucumber with spicy mayo sauce", spicy: true },
      { name: "Sockeye Salmon", price: "11.5", description: "Raw salmon & cucumber" },
      { name: "Alpha", price: "11.5", description: "Beef teriyaki & crabmeat deep fried with spicy mayo & unagi sauce", spicy: true },
      { name: "Chicken", price: "9.5", description: "Chicken & cucumber with unagi sauce & sesame seed" },
      { name: "Beef", price: "11", description: "Beef & cucumber with unagi sauce & sesame seed" },
      { name: "Spicy", price: "11", description: "Tuna, kimchi, cucumber with sriracha & spicy sauce", spicy: true },
      { name: "Candy", price: "11", description: "Smoked salmon, yam tempura, chili sauce & tempura flakes" },
      { name: "Rambo", price: "12", description: "Prawn tempura, cream cheese, avocado & crab with sweet mayo & unagi sauce" },
      { name: "Kootenay", price: "11.5", description: "Asparagus, yam tempura, seaweed, mango, avocado & blueberry sauce" },
      { name: "Philadelphia", price: "12.5", description: "Avocado, cucumber, cream cheese, crab meat, smoked salmon with sweet mayo sauce" },
      { name: "Crazy", price: "12", description: "Deep fried california roll with tempura flakes & sweet mayo, unagi sauce" },
      { name: "Yama", price: "12", description: "Yam tempura, crispy banana, mango, avocado with sweet mayo & blueberry sauce" },
      { name: "Crazy California", price: "12", description: "California roll & yam tempura, tempura flakes with unagi & sweet mayo sauce" },
      { name: "Cowboy", price: "10", description: "Prawn tempura, yam tempura & cucumber with unagi sauce" },
      { name: "Dynamite", price: "10", description: "Prawn tempura, cucumber, avocado & crabmeat with unagi sauce" },
      { name: "Alaska", price: "11.5", description: "California roll topped with raw salmon" },
    ],
  },
  {
    title: "Special Rolls",
    items: [
      { name: "Crispy Spicy Tuna", price: "14", description: "Spicy tuna, cucumber, tempura flakes, spicy & unagi sauce", spicy: true },
      { name: "Crispy Spicy Salmon", price: "14", description: "Spicy salmon, cucumber, tempura flakes, spicy & unagi sauce", spicy: true },
      { name: "Mango Tango", price: "15.5", description: "Apple, cream cheese on top mango with sweet mayo & blueberry sauce" },
      { name: "Caterpillar", price: "17", description: "Eel, crabmeat, cucumber, avocado on top with unagi, sweet mayo sauce" },
      { name: "Green Dragon", price: "17", description: "Prawn tempura, cucumber, crabmeat, avocado on top with sweet mayo and unagi sauce" },
      { name: "Black Dragon", price: "20", description: "Prawn tempura, crab meat, cucumber, avocado/tobiko on top with unagi & sweet mayo sauce" },
      { name: "Red Dragon", price: "18", description: "Prawn tempura, cucumber, crab meat, spicy salmon on top with tobiko & spicy sauce", spicy: true },
      { name: "O.M.G.", price: "20", description: "(2pc) Prawns, avocado, cucumber, yam tempura, spicy tuna and tobiko on top with spicy mayo & unagi sauce", spicy: true },
      { name: "Crazy Boy", price: "17", description: "Deep fried California, yam crunch, tempura flakes, sweet & spicy sauce, unagi sauce", spicy: true },
      { name: "Crazy Girl", price: "17", description: "Salmon, cream cheese, yam crunch, tempura flakes, deep fried with sweet & unagi sauce" },
      { name: "Popcorn", price: "18", description: "Deep fried scallop & prawn, cucumber, avocado, crabmeat & yam crunch with sweet mayo & unagi sauce" },
      { name: "Gangster", price: "20", description: "Cream cheese, smoked salmon, avocado, cucumber and salmon & BBQ eel on top with special sauce" },
      { name: "Hanabi", price: "18", description: "Prawn, crab, avocado, tamago, cucumber & yam crunch with unagi & sweet mayo sauce" },
      { name: "Rainbow", price: "19", description: "5 kinds of raw fish on top of a california roll with tobiko" },
      { name: "Torch Boy", price: "18.5", description: "Spicy tuna & cucumber topped with seared tuna & tobiko", spicy: true },
      { name: "Moon", price: "19", description: "Deep fried prawns, avocado, cucumber, crabmeat on top seared toro, unagi sauce" },
      { name: "Tsunami", price: "20", description: "Deep fried prawn, avocado, cucumber, spicy tuna and tuna tataki on top with unagi & spicy sauce", spicy: true },
      { name: "Hot Night", price: "19", description: "Prawn, crab, avocado, cucumber, spicy tuna on top with tobiko & spicy & unagi sauce", spicy: true },
      { name: "Hurricane", price: "20", description: "Prawn, yam crunch, asparagus, smoked salmon, yam, seaweed, with mango, avocado & chili sauce" },
      { name: "Tiger", price: "21", description: "Eel, avocado, cucumber, crab, top seared salmon, beet & spicy sauce, unagi sauce", spicy: true },
      { name: "Volcano", price: "21", description: "Prawn, yam crunch, crab, avocado, cucumber, yam on top seared tuna & scallop, tobiko with sweet & spicy sauce, unagi sauce", spicy: true },
      { name: "Spider", price: "22.5", description: "Softshell crab tempura, yam crunch, avocado, cucumber, crabmeat & masago with 3 sauces", spicy: true },
      { name: "Lobster", price: "35", description: "Lobster, crab, avocado on top seared salmon, masago & yam crunch with 3 sauces", spicy: true },
      { name: "Dream", price: "15", description: "Avocado, cucumber, salmon skin, & 2 fish by Chef's Choice with spicy sauce", spicy: true },
    ],
  },
  {
    title: "Oshizushi",
    items: [
      { name: "Salmon Oshi", price: "14.95", description: "Double layered Atlantic salmon, oshi sauce, jalapeno" },
      { name: "Sockeye Oshi", price: "16", description: "Double layered sockeye salmon, oshi sauce, jalapeno" },
      { name: "Unagi Oshi", price: "17", description: "Double layered unagi, oshi sauce, onion" },
      { name: "Hand Roll", price: "9", description: "Spicy Tuna/Salmon" },
    ],
  },
  {
    title: "Combos",
    items: [
      { name: "Sushi Wood A", price: "17", description: "California Roll, (3pc) Nigiri, Salmon, Tuna, Ebi" },
      { name: "Sushi Wood B", price: "18.5", description: "Dynamite Roll, (3pc) Nigiri" },
      { name: "Sushi Wood C", price: "20", description: "Yam Tempura Roll, (2pc) Nigiri, (4pc) Sashimi, Salmon, Tuna" },
      { name: "Salmon", price: "25.5", description: "Dynamite Roll, Spicy Salmon Roll, Salmon (2pc) Nigiri", spicy: true },
      { name: "Tuna", price: "25.5", description: "Dynamite Roll, Spicy Tuna Roll, Tuna (2pc) Nigiri", spicy: true },
      { name: "Dynamite", price: "27", description: "Dynamite Roll, Spicy Salmon Roll, Spicy Tuna Roll", spicy: true },
      { name: "Vegetable", price: "18", description: "Cucumber Roll, Avocado Roll & Vegetable Roll" },
      { name: "Mix", price: "33", description: "California Roll, Dynamite Roll, Spicy Salmon Roll, Spicy Tuna Roll", spicy: true },
      { name: "California", price: "22", description: "California Roll, Dynamite Roll, (1pc) Tuna, (1pc) Salmon (Nigiri)" },
      { name: "Love", price: "52", description: "California, Dynamite, Veggie, BC, Yam Rolls, (6pc) Nigiri" },
    ],
  },
  {
    title: "Boxes",
    note: "Lunch / Dinner",
    items: [
      { name: "Chicken", price: "18.95 / 23.95", description: "Chicken Teriyaki, California Roll, Salad, Tempura, Rice & Miso" },
      { name: "Beef", price: "20 / 25.5", description: "Beef Teriyaki, California Roll, Salad, Tempura, Rice & Miso" },
      { name: "Salmon", price: "20.95 / 26.95", description: "Salmon Teriyaki, California Roll, Salad, Tempura, Gyoza & Miso" },
      { name: "Veggie", price: "18.95 / 22.95", description: "Tofu Teriyaki, Veggie Roll, Salad, Tempura, Rice & Miso" },
      { name: "Sushi", price: "21.95 / 27.95", description: "Nigiri, California Roll, Salad, Tempura, Gyoza & Miso" },
      { name: "Sashimi & Sushi", price: "25.5 / 34", description: "Sashimi, Nigiri, Tempura, Salad, Gyoza & Miso" },
    ],
  },
  {
    title: "Party Trays",
    items: [
      { name: "Vegetable Tray", price: "45", description: "Yam Tempura Roll, Avocado, Cucumber Roll, Asparagus Roll, Veggie Roll, Crazy Veggie & House Salad" },
      { name: "Party Tray A", price: "59", description: "California Roll, Dynamite Roll, Spicy Salmon Roll, Spicy Tuna Roll, Yam Tempura Roll, BC Roll & Chicken Roll", spicy: true },
      { name: "Party Tray B", price: "98", description: "California Roll, Dynamite Roll, Spicy Salmon Roll, Spicy Tuna Roll, Yam Tempura Roll, BC Roll, Chicken Roll, (10pc) Nigiri & Appetizer Sashimi", spicy: true },
      { name: "Party Tray C", price: "140", description: "California Roll, Dynamite Roll, Spicy Salmon Roll, Yam Tempura Roll, BC Roll, Chicken Roll, (20pc) Nigiri & (20pc) Assorted Chef Sashimi", spicy: true },
      { name: "Sushi Wood Tray", price: "65", description: "(2) California Rolls, (2) Dynamite Rolls, Crispy Spicy Tuna, BC Roll, Salmon Maki, Tuna Maki & Cucumber Maki", spicy: true },
    ],
  },
  {
    title: "Yakisoba",
    note: "Pan fried egg noodle",
    items: [
      { name: "Chicken Yakisoba", price: "18" },
      { name: "Beef Yakisoba", price: "23" },
      { name: "Veggie Yakisoba", price: "17" },
    ],
  },
  {
    title: "Yakiudon",
    note: "Pan fried wheat noodle",
    items: [
      { name: "Chicken Yakiudon", price: "18" },
      { name: "Beef Yakiudon", price: "21" },
      { name: "Veggie Yakiudon", price: "17" },
    ],
  },
  {
    title: "Donburi",
    note: "Rice bowl with your choice",
    items: [
      { name: "Chicken Donburi", price: "17" },
      { name: "Beef Donburi", price: "17" },
      { name: "Chirashi (Assorted Sashimi)", price: "25" },
      { name: "Spicy Chirashi", price: "26", spicy: true },
      { name: "Unagi Donburi", price: "22" },
    ],
  },
  {
    title: "Teriyaki",
    note: "Stir fried veggies & rice, miso",
    items: [
      { name: "Chicken Teriyaki", price: "21.5" },
      { name: "Beef Teriyaki", price: "21.5" },
      { name: "Salmon Teriyaki", price: "23.95" },
      { name: "Tofu Teriyaki", price: "18.95" },
    ],
  },
  {
    title: "Udon",
    note: "Thick wheat noodle soup",
    items: [
      { name: "Chicken Udon", price: "18" },
      { name: "Beef Udon", price: "20" },
      { name: "Veggie Udon", price: "16" },
      { name: "Spicy Seafood Udon", price: "19.5", spicy: true },
      { name: "Pork Udon", price: "18" },
      { name: "Tempura Udon", price: "18.5" },
    ],
  },
  {
    title: "Ramen",
    note: "Soybean paste wheat noodle soup",
    items: [
      { name: "Chicken Ramen", price: "18.5" },
      { name: "Beef Ramen", price: "22" },
      { name: "Pork Ramen", price: "19" },
      { name: "Veggie Ramen", price: "16" },
      { name: "Shoyu Ramen", price: "18" },
      { name: "Miso Ramen", price: "18" },
      { name: "Shio Ramen", price: "18" },
      { name: "Tonkotsu Ramen", price: "19" },
    ],
  },
  {
    title: "Tonkatsu",
    note: "Deep fried breaded with egg, pork, lettuce w/rice & soup",
    items: [
      { name: "Original Tonkatsu", price: "20.95" },
      { name: "Spicy Tonkatsu", price: "21.95", spicy: true },
    ],
  },
  {
    title: "Korean Cuisine",
    items: [
      { name: "Bulgogi", price: "26.95", description: "Potato noodle, thinly sliced beef and veggies in house made sauce served with rice and soup" },
      { name: "Spicy Dak", price: "26.95", description: "Thinly sliced chicken and veggies in house made sauce, served with rice and soup", spicy: true },
      { name: "Jeyuk Bokkeum", price: "26.95", description: "Stir-fried pork and veggies served with rice and soup (with cheese +2)", spicy: true },
      { name: "Kimchi Fried Rice", price: "19.95", description: "Stir-fried rice with kimchi and pork topped with fried egg, served with soup", spicy: true },
      { name: "Shrimp Fried Rice", price: "23.95", description: "Stir-fried rice with shrimp, egg, veggies, served with soup" },
      { name: "Chicken Fried Rice", price: "20" },
      { name: "Vegetable Fried Rice", price: "18" },
      { name: "Kimchi Jjigae", price: "19.5", description: "House made kimchi and pork stew with tofu, served with rice", spicy: true },
      { name: "Kimchi Jjigae with Tomato", price: "20.5", description: "House made kimchi and tomato and pork stew with tofu, served with rice" },
      { name: "Pork Gyoza Soup", price: "12.95" },
      { name: "Soondubu Jjigae", price: "22.5", description: "Spicy soft tofu stew, seafood and egg, served with rice", spicy: true },
      { name: "Stone Bibimbap", price: "25", description: "Steamed rice bowl with mixed veggies, sliced beef and egg with house made sauce, served with soup" },
      { name: "Galbi", price: "27", description: "Beef short-ribs with authentic Korean BBQ and house made sauce" },
      { name: "Japchae (Beef)", price: "22.95", description: "Beef, stir-fried sweet potato noodles and veggies, house made sauce" },
      { name: "Japchae (Veggie)", price: "19", description: "Mixed vegetables, stir-fried sweet potato noodles, house made sauce" },
    ],
  },
  {
    title: "Kids Menu",
    items: [
      { name: "Teriyaki Chicken", price: "14", description: "Edamame, Teriyaki Chicken, Salad, with Rice or Noodles, Mochi Ice Cream" },
      { name: "Teriyaki Beef", price: "16", description: "Edamame, Teriyaki Beef, Salad, with Rice or Noodles, Mochi Ice Cream" },
    ],
  },
  {
    title: "Desserts",
    items: [
      { name: "Cream Cheese Cake", price: "12", description: "Deep Fried Cream Cheese" },
      { name: "Ice Cream", price: "10", description: "3 scoops (Matcha/Mango)" },
      { name: "Ice Cream Mochi", price: "10", description: "Mochi/Matcha, Strawberry, Mango" },
    ],
  },
];

const nelsonMenu: MenuSection[] = [
  {
    title: "Appetizers",
    items: [
      { name: "Kimchi", price: "7.95", spicy: true },
      { name: "Edamame", price: "7.95" },
      { name: "Gomae Salad", price: "8.5", description: "Spinach" },
      { name: "Tuna Gomae Salad", price: "11.95", description: "Spinach" },
      { name: "Seaweed Salad", price: "7.95" },
      { name: "House Salad", price: "9.5" },
      { name: "Smoked Salmon Salad", price: "15.95" },
      { name: "Chicken Salad", price: "14.5" },
      { name: "Spicy Sashimi Salad", price: "16.95", description: "Assorted sashimi with mixed greens & a spicy sauce", spicy: true },
      { name: "Spicy Ebi Mayo Salad", price: "16.95", description: "Deep fried shrimp with salad, spicy mayo sauce", spicy: true },
      { name: "Salmon & Tuna Carpaccio", price: "19.5", description: "8 pcs of raw fish with salad, ponzu sauce" },
      { name: "Mix Sashimi Carpaccio", price: "21.5", description: "8 pcs of raw fish with salad, ponzu sauce" },
      { name: "Spicy Agedashi Tofu", price: "10.95", description: "(6pc) Crispy fried tofu with a spicy sauce", spicy: true },
      { name: "Agedashi Cheese", price: "11.95", description: "(6pc)" },
      { name: "Agedashi Tofu", price: "10.25", description: "(6pc) Crispy fried tofu with teriyaki sauce" },
      { name: "Takoyaki (Octopus)", price: "10.5", description: "(6pc)" },
      { name: "Deep Fried Pickle", price: "10.95" },
      { name: "Spicy Pork Gyoza", price: "11.95", description: "(6pc)", spicy: true },
      { name: "Veggie Gyoza / Pork Gyoza", price: "10.5" },
      { name: "French Fries", price: "8.95" },
      { name: "Chicken Karaage", price: "13.5" },
      { name: "Soft Shell Crab", price: "15.95", description: "Deep fried soft shell crab" },
      { name: "Calamari", price: "12.5", description: "Deep fried squid" },
      { name: "Vegetable Spring Roll", price: "10.5", description: "(6pc)" },
      { name: "Ebi Sunomono", price: "9.95" },
      { name: "Vegetable Sunomono", price: "8.95" },
      { name: "Fried Oysters", price: "12.95" },
      { name: "Pork Gyoza Soup", price: "14.95" },
      { name: "Crunch Jalapeno", price: "12.5", description: "Crispy fried jalapeno with tuna / salmon", spicy: true },
      { name: "Spicy Chicken", price: "18.5", description: "Deep fried chicken with a homemade sauce", spicy: true },
      { name: "Prawn Tempura", price: "10.95 / 17.95", description: "6pc / 8pc" },
      { name: "Veggie Tempura", price: "10.5 / 17.5", description: "5pc / 10pc" },
      { name: "Mixed Tempura", price: "10.95 / 17.95", description: "4pc / 10pc" },
      { name: "Yam Tempura", price: "9.5 / 16.5", description: "4pc / 8pc" },
      { name: "Monkey Brain", price: "16.95", description: "Whole avocado deep fried & filled with spicy tuna & crabmeat", spicy: true },
      { name: "Rice", price: "3.25" },
      { name: "Miso", price: "3.25" },
    ],
  },
  {
    title: "Nigiri",
    note: "Price per 2 pcs",
    items: [
      { name: "Tamago (Egg)", price: "6.5" },
      { name: "Ebi (Cooked Prawn)", price: "7" },
      { name: "Tako (Octopus)", price: "8" },
      { name: "Toro (Tuna Belly)", price: "9.5" },
      { name: "Kani (Real Crab)", price: "9.5" },
      { name: "Salmon", price: "7" },
      { name: "Chopped Scallop", price: "8" },
      { name: "Avocado", price: "5.5" },
      { name: "Masago (Smelt Roe)", price: "7" },
      { name: "Ika (Squid)", price: "7.5" },
      { name: "Ikura (Salmon Roe)", price: "8" },
      { name: "Mango", price: "5.5" },
      { name: "Tobiko (Flying Fish Roe)", price: "8" },
      { name: "Sockeye Salmon", price: "9" },
      { name: "Seared Salmon", price: "7.5" },
      { name: "Ahi Tuna", price: "9" },
      { name: "Seared Tuna", price: "7.5" },
      { name: "Tai", price: "7" },
      { name: "Inari", price: "7" },
      { name: "Tuna", price: "7" },
      { name: "Unagi", price: "8" },
    ],
  },
  {
    title: "Sashimi",
    note: "4 pcs / 8 pcs",
    items: [
      { name: "Appetizer (7 pcs)", price: "17.5" },
      { name: "Assorted (15 pcs)", price: "33.95" },
      { name: "Chef (20 pcs)", price: "45.95" },
      { name: "Unagi (Eel)", price: "11.95 / 21.95" },
      { name: "Tako (Octopus)", price: "10.95 / 20.95" },
      { name: "Spicy Salmon", price: "12.95 / 23.95", spicy: true },
      { name: "Spicy Tuna", price: "12.95 / 23.95", spicy: true },
      { name: "Tuna Tataki", price: "12.95 / 23.95" },
      { name: "Ahi Tuna", price: "14.95 / 26.95" },
      { name: "Salmon", price: "11.95 / 21.95" },
      { name: "Sockeye Salmon", price: "12.95 / 23.95" },
      { name: "Tuna", price: "11.95 / 21.95" },
      { name: "Toro", price: "12.95 / 23.95" },
    ],
  },
  {
    title: "Rolls",
    items: [
      { name: "Cucumber Maki", price: "5.95" },
      { name: "Tuna Maki", price: "6.95" },
      { name: "Avocado Maki", price: "6.5" },
      { name: "Salmon Maki", price: "6.95" },
      { name: "Vegetable", price: "7.95", description: "Cucumber, avocado, asparagus & yam" },
      { name: "BC", price: "8.5", description: "Salmon, cucumber & crabmeat" },
      { name: "California", price: "7.95", description: "Cucumber, avocado & crabmeat" },
      { name: "Real Crab California", price: "13.95", description: "Real crab, avocado & cucumber" },
      { name: "Fresh Vegetable", price: "7.95", description: "Cucumber, avocado, carrot, beet, seaweed & radish" },
      { name: "Yam Tempura", price: "7.95" },
      { name: "Tempura", price: "8.25", description: "(2pc) Prawn tempura & avocado" },
      { name: "Asparagus", price: "7.95", description: "Cooked asparagus, avocado" },
      { name: "Tofu", price: "7.95", description: "Deep fried tofu with special sauce" },
      { name: "Avocado & Cucumber", price: "7.5" },
      { name: "Avocado & Tuna", price: "8.95" },
      { name: "Avocado & Salmon", price: "8.95" },
      { name: "Avocado & Mango", price: "7.95" },
      { name: "Negitoro", price: "9.95", description: "Toro & green onion" },
      { name: "Unagi", price: "9.95", description: "Eel, cucumber, avocado & crabmeat" },
      { name: "Crazy Veggie", price: "10.5", description: "Assorted veggie tempura" },
      { name: "Spicy Salmon Tempura", price: "9.5", spicy: true },
      { name: "Spicy Tuna Tempura", price: "9.5", description: "Tuna tempura, cucumber & crabmeat", spicy: true },
      { name: "Chopped Scallop", price: "9.95", description: "Scallop, cucumber, masago & sweet mayo" },
      { name: "Spicy Salmon", price: "8.95", description: "Raw salmon & cucumber", spicy: true },
      { name: "Spicy Tuna", price: "8.95", description: "Raw tuna & cucumber", spicy: true },
      { name: "Sockeye Salmon", price: "8.95", description: "Raw salmon & cucumber" },
      { name: "Alpha", price: "10.95", description: "Beef teriyaki & crabmeat deep fried with spicy mayo & unagi sauce", spicy: true },
      { name: "Chicken", price: "9.25", description: "Chicken & cucumber with teriyaki sauce" },
      { name: "Beef", price: "9.25", description: "Beef & cucumber with teriyaki sauce" },
      { name: "Popeye", price: "8.25", description: "Spinach, avocado & sesame sauce" },
      { name: "Rambo", price: "10.95", description: "Prawn tempura, cream cheese, avocado & crab" },
      { name: "Kootenay", price: "10.95", description: "Asparagus, yam tempura, seaweed, mango & avocado" },
      { name: "Candy", price: "10.95", description: "Smoked salmon, yam tempura, chili sauce & tempura flakes" },
      { name: "Philadelphia", price: "12.95", description: "Avocado, cucumber, cream cheese, crabmeat, smoked salmon & mayo sauce" },
      { name: "Yama", price: "10.95", description: "Yam tempura, banana, mango, avocado & mayo sauce" },
      { name: "Crazy California", price: "10.95", description: "California roll & yam tempura with teriyaki sauce" },
      { name: "Cowboy", price: "8.95", description: "Prawn tempura, yam tempura & cucumber" },
      { name: "Dynamite", price: "8.95", description: "Prawn tempura, cucumber, avocado & crabmeat" },
      { name: "Crazy", price: "10.95", description: "Deep fried California roll" },
      { name: "Alaska", price: "10.5", description: "California roll & avocado topped with raw salmon" },
      { name: "Spicy", price: "9.95", description: "Tuna, kimchi, cucumber & masago", spicy: true },
      { name: "S.A.C", price: "10.5", description: "Salmon, avocado, cream cheese" },
      { name: "Avocado Yam", price: "8.5" },
      { name: "Inari", price: "8.95", description: "Inari, cucumber, avocado" },
      { name: "Mango Salmon Avocado", price: "10.95" },
      { name: "Mango Tuna Avocado", price: "10.95" },
      { name: "Mango Gomae", price: "8.95" },
      { name: "Mango Salmon", price: "9.5" },
      { name: "Mango Inari", price: "8.95" },
      { name: "Cream Cheese Yam", price: "8.95" },
      { name: "Cream Cheese Mango", price: "9.95" },
      { name: "Cream Cheese Salmon", price: "9.95" },
      { name: "Cream Cheese Tuna", price: "9.95" },
      { name: "Yummy", price: "11.95", description: "Mango, avocado, cucumber, cream cheese" },
      { name: "Futo", price: "12.95", description: "Crabmeat, avocado, cucumber, egg, inari, seaweed salad" },
    ],
  },
  {
    title: "Special Rolls",
    items: [
      { name: "Crispy Spicy Tuna", price: "13.95", description: "Spicy tuna, cucumber, tempura flakes, spicy sauce & green onion", spicy: true },
      { name: "Crispy Spicy Salmon", price: "13.95", description: "Spicy salmon, cucumber, tempura flakes, spicy sauce & green onion", spicy: true },
      { name: "Mango Tango", price: "14.5", description: "Mango, pineapple, cream cheese on top of mango, mango sauce, special sauce" },
      { name: "Caterpillar", price: "16.5", description: "Eel, crabmeat, cucumber, covered with avocado & salad" },
      { name: "Green Dragon", price: "15.75", description: "Prawn tempura, cucumber, crabmeat, with avocado on top" },
      { name: "Black Dragon", price: "16.95", description: "Prawn tempura, crab, cucumber, avocado — on top unagi & shrimp, masago" },
      { name: "Red Dragon", price: "16.95", description: "Prawn tempura, avocado, cucumber, crab, masago, spicy salmon", spicy: true },
      { name: "Purple Dragon", price: "16.95", description: "Prawn tempura, cucumber, crab — on top avocado, BBQ eel, beet, green onion & tobiko" },
      { name: "O.M.G.", price: "18.5", description: "(2pc) Prawns, avocado, cucumber, yam tempura, spicy tuna, spicy mayo & tobiko on top & green onion", spicy: true },
      { name: "Crazy Boy", price: "15.95", description: "Deep fried California, yam crunch, sweet & spicy sauce", spicy: true },
      { name: "Crazy Girl", price: "15.95", description: "Salmon, cream cheese, yam crunch, deep fried with sweet sauce" },
      { name: "Popcorn", price: "16.95", description: "Deep fried scallop & prawn, cucumber, avocado, yam crunch & crab" },
      { name: "Hanabi", price: "16.5", description: "Prawn, crab, avocado, tamago, cucumber & yam crunch" },
      { name: "Rainbow", price: "17.5", description: "5 kinds of raw fish on top of a California roll with tobiko" },
      { name: "Moon", price: "18.95", description: "Deep fried prawn, avocado, cucumber, crabmeat — on top seared toro" },
      { name: "Awesome", price: "18.5", description: "Spicy salmon, raw tuna & avocado wrapped in cucumber", spicy: true },
      { name: "Gangster", price: "18.95", description: "Cream cheese, smoked salmon, avocado, cucumber on top salmon, BBQ eel & special sauce" },
      { name: "Tsunami", price: "18.95", description: "Deep fried prawn, avocado, cucumber, spicy tuna with tataki", spicy: true },
      { name: "Hot Night", price: "17.95", description: "Spicy tuna, prawn, crab, avocado, cucumber, masago & green onion", spicy: true },
      { name: "Hurricane", price: "17.95", description: "Prawn, asparagus, smoked salmon, yam, seaweed, with mango, avocado & chili sauce" },
      { name: "Mountain Fever", price: "19.5", description: "Deep fried prawn, pineapple, tempura & cream cheese on top mango, smoked salmon with tuna tataki" },
      { name: "Tiger", price: "19.5", description: "Eel, avocado, cucumber, crab, top seared salmon, beet & spicy sauce", spicy: true },
      { name: "Volcano", price: "19.5", description: "Prawn, crab, avocado, cucumber, yam on top seared tuna & scallop, tobiko with sweet & spicy sauce", spicy: true },
      { name: "Spider", price: "22.5", description: "Softshell crab tempura, avocado, cucumber, crabmeat & tobiko", spicy: true },
      { name: "Lobster", price: "24.95", description: "Lobster, crab, prawn, cucumber, avocado on top seared salmon, masago & yam crunch", spicy: true },
      { name: "Fantastic", price: "20.5", description: "Eel, tuna, jalapeno, cucumber, green onion, avocado, crabmeat, masago", spicy: true },
      { name: "Amazing", price: "20.5", description: "Prawn, avocado, cucumber, cream cheese, crabmeat on top torched scallop, tamago" },
      { name: "Tuna Tataki", price: "16.5", description: "Inside: prawn, crabmeat, avocado, cucumber. Outside: seared tuna, green onion, ponzu sauce" },
      { name: "Beef Tataki", price: "16.5", description: "Inside: prawn, crabmeat, avocado, cucumber. Outside: seared beef, green onion, ponzu sauce, spicy mayo", spicy: true },
      { name: "French Kiss", price: "18.5", description: "Inside: prawn, crabmeat, avocado, cucumber, cream cheese. Outside: spicy salmon, torched unagi, unagi sauce, spicy mayo" },
      { name: "Hawaiian", price: "16.95", description: "Outside: mango, avocado, salad, mango sauce & sweet chili sauce" },
      { name: "Happy Mango", price: "15.95", description: "Cream cheese, yam, cucumber. Outside: smoked salmon, mango, tobiko, sweet chili sauce, teriyaki sauce" },
      { name: "Unagi Philly", price: "14.95", description: "Inside: unagi, cream cheese, cucumber, avocado, deep fried. Outside: yam crunch, unagi sauce, spicy mayo" },
      { name: "Fire Dynamite", price: "15.5", description: "Inside: dynamite. Outside: smoked salmon, tobiko, unagi sauce, spicy mayo", spicy: true },
      { name: "Mango Paradise", price: "14.95", description: "Inside: mango, avocado, cucumber. Outside: salmon with crunch, mango sauce, unagi sauce" },
      { name: "House", price: "17.95", description: "Inside: tuna, crabmeat, avocado, cucumber. Outside: seared salmon, masago, spicy mayo, unagi sauce" },
      { name: "Sushiwood", price: "19.95", description: "Inside: real crabmeat, cucumber, mango, cream cheese. Outside: avocado, tobiko, masago, unagi sauce, sweet mayo" },
      { name: "Sakura", price: "19.5", description: "Inside: spicy tuna, cucumber, deep fried. Outside: chopped scallop torched, tobiko, masago, green onion, salad, spicy mayo", spicy: true },
      { name: "Sunset", price: "19.95", description: "Inside: prawn, crabmeat, cream cheese, yam crunch, tobiko, unagi sauce, sweet mayo, sweet chili sauce" },
    ],
  },
  {
    title: "Combos",
    items: [
      { name: "Sushi Wood A", price: "13.95", description: "California roll, 3pc nigiri" },
      { name: "Sushi Wood B", price: "14.95", description: "Dynamite roll, 3pc nigiri" },
      { name: "Sushi Wood C", price: "19.95", description: "Yam tempura roll, 2pc nigiri, 4pc sashimi" },
      { name: "Veggie", price: "17.95", description: "Cucumber roll, avocado roll & asparagus roll" },
      { name: "California", price: "19.5", description: "California roll, dynamite roll, tuna 1pc, salmon 1pc (nigiri)" },
      { name: "Salmon", price: "20.5", description: "Dynamite roll, spicy salmon roll, salmon 2pc (nigiri)", spicy: true },
      { name: "Tuna", price: "20.5", description: "Dynamite roll, spicy tuna roll, tuna 2pc (nigiri)", spicy: true },
      { name: "Dynamite", price: "21.5", description: "Dynamite roll, spicy salmon roll, spicy tuna roll", spicy: true },
      { name: "Mix", price: "27.5", description: "California roll, dynamite roll, spicy salmon roll, spicy tuna roll", spicy: true },
      { name: "Love", price: "49.5", description: "California roll, dynamite roll, veggie roll, BC roll, yam tempura roll, nigiri 6pc" },
    ],
  },
  {
    title: "Boxes",
    note: "Lunch / Dinner",
    items: [
      { name: "Chicken", price: "18.95 / 23.95", description: "Chicken teriyaki, California roll, salad, tempura & rice" },
      { name: "Beef", price: "18.95 / 23.95", description: "Beef teriyaki, California roll, salad, tempura & rice" },
      { name: "Veggie", price: "18.95 / 22.95", description: "Tofu teriyaki, veggie roll, salad, tempura & rice" },
      { name: "Salmon", price: "20.95 / 26.95", description: "Salmon teriyaki, California roll, salad, tempura & pork gyoza" },
      { name: "Sushi", price: "21.95 / 27.95", description: "Nigiri, California roll, tempura, salad & gyoza" },
      { name: "Sashimi & Sushi", price: "23.95 / 29.95", description: "Salmon and tuna sashimi, nigiri, tempura, salad & gyoza" },
    ],
  },
  {
    title: "Party Trays",
    items: [
      { name: "Vegetable Tray", price: "48.95", description: "Yam tempura roll, avo & cucumber roll, popeye roll, asparagus roll, veggie roll, crazy veggie roll & house salad" },
      { name: "Party Tray A", price: "54.95", description: "California roll, dynamite roll, spicy salmon roll, spicy tuna roll, yam tempura roll, BC roll & chicken roll", spicy: true },
      { name: "Party Tray B", price: "89.95", description: "California roll, dynamite roll, spicy salmon roll, spicy tuna roll, yam tempura roll, BC roll, chicken roll, 10pc nigiri & appetizer sashimi 6pc", spicy: true },
      { name: "Party Tray C", price: "128.95", description: "California roll, dynamite roll, spicy salmon roll, spicy tuna roll, yam tempura roll, BC roll, chicken roll, 20pc nigiri & assorted chef sashimi 20pc", spicy: true },
      { name: "Sushi Wood Tray", price: "63.95", description: "2 California rolls, 2 dynamite rolls, crispy spicy tuna roll, BC roll, salmon maki, tuna maki & cucumber maki" },
    ],
  },
  {
    title: "Yakisoba or Yakiudon",
    note: "Pan fried egg or wheat noodle",
    items: [
      { name: "Chicken", price: "17.95" },
      { name: "Beef", price: "17.95" },
      { name: "Veggie", price: "15.5" },
      { name: "Kimchi", price: "15.5" },
    ],
  },
  {
    title: "Udon",
    note: "Thick wheat noodle soup",
    items: [
      { name: "Chicken Udon", price: "16.95" },
      { name: "Beef Udon", price: "17.95" },
      { name: "Veggie Udon", price: "15.5" },
      { name: "Spicy Seafood Udon", price: "19", spicy: true },
      { name: "Tempura Udon", price: "17.95" },
      { name: "Pork Udon", price: "17.95" },
      { name: "Kimchi Udon", price: "15.45" },
    ],
  },
  {
    title: "Ramen",
    note: "Soybean paste wheat noodle",
    items: [
      { name: "Chicken Ramen", price: "16.95" },
      { name: "Beef Ramen", price: "16.95" },
      { name: "Veggie Ramen", price: "15.95" },
      { name: "Pork Ramen", price: "17.5" },
    ],
  },
  {
    title: "Teriyaki",
    note: "Stir fried veggies & rice, miso",
    items: [
      { name: "Chicken Teriyaki", price: "21.5" },
      { name: "Beef Teriyaki", price: "21.5" },
      { name: "Tofu Teriyaki", price: "18.95" },
      { name: "Salmon Teriyaki", price: "23.95" },
    ],
  },
  {
    title: "Donburi",
    note: "Rice bowl with your choice",
    items: [
      { name: "Chicken Donburi", price: "16.95" },
      { name: "Beef Donburi", price: "16.95" },
      { name: "Veggie Donburi", price: "15.95" },
      { name: "Chirashi (Assorted Sashimi)", price: "25.5" },
      { name: "Spicy Chirashi", price: "25.95", spicy: true },
      { name: "Unagi Donburi", price: "19.95" },
    ],
  },
  {
    title: "Korean Soup",
    note: "Comes with one bowl of steamed rice",
    items: [
      { name: "Galbi-tang", price: "25", description: "Hearty beef soup with beef ribs, egg, and sweet potato noodles" },
      { name: "Pork Rib Soup", price: "23.95", description: "Hearty pork bone soup with assorted vegetables", spicy: true },
      { name: "Soondubu Jjigae", price: "21.5", description: "Korean spicy soft tofu with egg & seafood", spicy: true },
      { name: "Kimchi Jjigae", price: "19.5", description: "Hearty and spicy kimchi soup with vegetables, diced tofu, and pork", spicy: true },
      { name: "Dakgae-jang", price: "21.5", description: "Spicy chicken soup with vegetables", spicy: true },
      { name: "Doenjang Jjigae", price: "19.5", description: "Korean style bean paste soup with vegetables" },
      { name: "Beef Stone", price: "21.95", description: "Beef stone bowl soup with potato noodle, green onion" },
    ],
  },
  {
    title: "Korean Barbecue",
    note: "Comes with one bowl of steamed rice",
    items: [
      { name: "Bulgogi", price: "26.95", description: "Stir-fry of thinly sliced beef in a house special marinade" },
      { name: "Spicy Pork", price: "26.95", description: "Grilled thinly sliced tender pork marinated in chilli pepper sauce", spicy: true },
      { name: "Spicy Dak", price: "26.95", description: "Grilled thinly sliced tender chicken marinated in chilli pepper sauce", spicy: true },
      { name: "Galbi", price: "29.95", description: "Beef short-ribs marinated in authentic Korean barbecue sauce" },
    ],
  },
  {
    title: "BBQ Fried Chicken",
    note: "Boneless",
    items: [
      { name: "Sweet & Spicy Chicken", price: "23.95", spicy: true },
      { name: "Soy Garlic Chicken", price: "23.95" },
    ],
  },
  {
    title: "Stir Fried Rice",
    items: [
      { name: "Kimchi Fried Rice", price: "19.95", description: "Stir-fried rice with kimchi & pork topped with fried egg, salad, miso", spicy: true },
      { name: "Shrimp Fried Rice", price: "22.95", description: "Stir-fried rice with shrimp, egg, veggies with salad, miso" },
      { name: "Chicken Fried Rice", price: "22.95", description: "Stir-fried rice with chicken, egg, veggies with salad, miso" },
      { name: "Bibimbab", price: "20.95", description: "Rice bowl with mixed veggies, sliced beef, egg with spicy sauce, miso" },
      { name: "Stone Bibimbab", price: "24.95", description: "Steamed rice bowl with mixed veggies, sliced beef, egg with spicy sauce, miso" },
    ],
  },
  {
    title: "Noodle & Special Dish",
    items: [
      { name: "Japchae", price: "22.95", description: "Stir-fried sweet potato noodles in sweet sesame oil with beef and mixed vegetables" },
      { name: "Spicy Rice Cake", price: "14.5", description: "Royal cuisine-version of Korean rice cakes with assorted vegetables", spicy: true },
      { name: "Hotdog", price: "8", description: "Korean-style hotdog (cheese & sausage or cheese & potato)" },
      { name: "Seafood Pancake", price: "28.5", description: "Savoury wheat-flour pancake made with shrimp, squid and green onions" },
      { name: "Kimchi Pancake", price: "19.5", description: "Tasty wheat flour pancake with chopped kimchi and onions", spicy: true },
    ],
  },
  {
    title: "Korean Combo",
    items: [
      { name: "Beef Combo", price: "20.95", description: "Beef, rice, salad, noodle" },
      { name: "Pork Combo", price: "20.95", description: "Spicy pork, rice, salad, noodle", spicy: true },
      { name: "Chicken Combo", price: "20.95", description: "Spicy chicken, rice, salad, noodle", spicy: true },
      { name: "Fried Chicken Combo", price: "20.95", description: "Fried chicken, rice, salad, noodle" },
      { name: "Tofu Combo", price: "17.5", description: "Tofu, rice, salad, noodle" },
    ],
  },
];

export const menus: Partial<Record<"fernie" | "nelson" | "castlegar", MenuSection[]>> = {
  fernie: fernieMenu,
  nelson: nelsonMenu,
};

// schema.org Menu markup for the Restaurant structured data
export function menuSchema(location: "fernie" | "nelson" | "castlegar") {
  const sections = menus[location];
  if (!sections) return undefined;

  return {
    "@type": "Menu",
    name: `SushiWood ${location.charAt(0).toUpperCase() + location.slice(1)} Menu`,
    hasMenuSection: sections.map((section) => ({
      "@type": "MenuSection",
      name: section.title,
      ...(section.note ? { description: section.note } : {}),
      hasMenuItem: section.items.map((item) => ({
        "@type": "MenuItem",
        name: item.name,
        ...(item.description ? { description: item.description } : {}),
        // Only emit an Offer for plain single prices (dual "lunch / dinner" prices stay descriptive)
        ...(/^\d+(\.\d+)?$/.test(item.price)
          ? { offers: { "@type": "Offer", price: item.price, priceCurrency: "CAD" } }
          : {}),
      })),
    })),
  };
}
